name: PackageAndPublish

on:
  release:
    types: [ released ]
    branches: [ main ]

jobs:
  id:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Boom.IdType/Boom.IdType.csproj -c Release --no-restore

      - name: Test
        run: dotnet test ./Boom.IdType.UnitTests/Boom.IdType.UnitTests.csproj -c Release --no-restore

      - name: Package
        run: dotnet pack ./Boom.IdType/Boom.IdType.csproj -c Release --no-restore -o out -p:PackageVersion=${{github.ref_name}}
        
      - name: Push to Nuget
        run: dotnet nuget push ./out/BoomPP.IdType.${{github.ref_name}}.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
          
  id-entityframework:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Update ID package
        run: dotnet add ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.csproj package BoomPP.IdType -v ${{github.ref_name}} --no-restore
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.csproj -c Release --no-restore

      #- name: Test
      #  run: dotnet test ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.UnitTests.csproj -c Release --no-restore

      - name: Package
        run: dotnet pack ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.csproj -c Release --no-restore -o out -p:PackageVersion=${{github.ref_name}}

      - name: Push to Nuget
        run: dotnet nuget push ./out/BoomPP.IdType.EntityFramework.${{github.ref_name}}.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
