name: PackageAndPublish

on:
  release:
    types: [ released ]
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Boom.Id --no-restore

      - name: Test
        run: dotnet test ./Boom.Id.UnitTests --no-build

      - name: Package
        run: dotnet pack --no-build -c Release -o out

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: tedd/publish-nuget-neo@v1
        with:
          PROJECT_FILE_PATH: 'Boom.Id/Boom.Id.csproj'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: true