name: PackageAndPublish

on:
  release:
    types: [ released ]
    branches: [ main ]

jobs:
  id:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./Boom.IdType/Boom.IdType.csproj -c Release --no-restore

      - name: Test
        run: dotnet test ./Boom.IdType.UnitTests/Boom.IdType.UnitTests.csproj -c Release --no-restore

      - name: Package
        run: dotnet pack ./Boom.IdType/Boom.IdType.csproj -c Release --no-restore -o out

      # Publish
      - name: Publish to Nuget
        id: publish_nuget
        uses: tedd/publish-nuget-neo@v1
        with:
          PROJECT_FILE_PATH: ./Boom.IdType/Boom.IdType.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false
          TAG_FORMAT: "*"
          REBUILD_PROJECT: false
          VERSION_STATIC: ${{github.ref_name}}
          
#  id-entityframework:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: 8.x
#
#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Build
#        run: dotnet build ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.csproj -c Release --no-restore
#
#      #- name: Test
#      #  run: dotnet test ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.UnitTests.csproj -c Release --no-restore
#
#      - name: Package
#        run: dotnet pack ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.csproj -c Release --no-restore -o out
#
#      # Publish
#      - name: Publish to Nuget
#        id: publish_nuget
#        uses: tedd/publish-nuget-neo@v1
#        with:
#          PROJECT_FILE_PATH: ./Boom.IdType.EntityFramework/Boom.IdType.EntityFramework.csproj
#          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
#          TAG_COMMIT: true
#          REBUILD_PROJECT: false